import { useState, type SVGProps } from "react";

type IconProps = SVGProps<SVGSVGElement>;

const Menu = (props: IconProps) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    {...props}
  >
    <line x1="4" y1="6" x2="20" y2="6" />
    <line x1="4" y1="12" x2="20" y2="12" />
    <line x1="4" y1="18" x2="20" y2="18" />
  </svg>
);

const Search = (props: IconProps) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    {...props}
  >
    <circle cx="11" cy="11" r="7" />
    <line x1="16.65" y1="16.65" x2="21" y2="21" />
  </svg>
);

const Plus = (props: IconProps) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    {...props}
  >
    <line x1="12" y1="5" x2="12" y2="19" />
    <line x1="5" y1="12" x2="19" y2="12" />
  </svg>
);

const Send = (props: IconProps) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    {...props}
  >
    <line x1="22" y1="2" x2="11" y2="13" />
    <polygon points="22 2 15 22 11 13 2 9 22 2" />
  </svg>
);

type ChatMessage = {
  role: "user" | "assistant";
  content: string;
};

type Chat = {
  id: number;
  title: string;
  recent: boolean;
  messages: ChatMessage[];
};

export const StudyGuruChat = () => {
  const [message, setMessage] = useState("");
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [chats, setChats] = useState<Chat[]>([
    {
      id: 1,
      title: "History file 1",
      recent: true,
      messages: [
        { role: "user", content: "Tell me about the French Revolution" },
        {
          role: "assistant",
          content:
            "The French Revolution was a period of radical social and political change in France from 1789 to 1799. It led to the end of the monarchy and establishment of a republic.",
        },
      ],
    },
    {
      id: 2,
      title: "Helping HHR 2",
      recent: true,
      messages: [
        { role: "user", content: "What is HHR?" },
        {
          role: "assistant",
          content:
            "HHR can stand for different things depending on context. Could you provide more details about what you're referring to?",
        },
      ],
    },
    {
      id: 3,
      title: "Chat 3",
      recent: true,
      messages: [],
    },
  ]);
  const [activeChatId, setActiveChatId] = useState<number>(1);

  const activeChat = chats.find((chat) => chat.id === activeChatId) || null;

  const handleNewChat = () => {
    const newChat: Chat = {
      id: Date.now(),
      title: `New Chat ${chats.length + 1}`,
      recent: true,
      messages: [],
    };
    setChats([newChat, ...chats]);
    setActiveChatId(newChat.id);
  };

  const handleDeleteChat = (id: number) => {
    setChats((prev) => {
      const updated = prev.filter((chat) => chat.id !== id);
      if (!updated.some((chat) => chat.id === activeChatId)) {
        setActiveChatId(updated.length ? updated[0].id : 0);
      }
      return updated;
    });
  };

  const handleSend = () => {
    if (!message.trim() || !activeChat) return;

    setChats((prevChats) =>
      prevChats.map((chat) => {
        if (chat.id !== activeChatId) return chat;

        const newMessages: ChatMessage[] = [
          ...chat.messages,
          { role: "user", content: message },
          {
            role: "assistant",
            content:
              "This is a sample response from Study Guru. In a real application, this would be generated by AI.",
          },
        ];

        return {
          ...chat,
          messages: newMessages,
        };
      })
    );

    setMessage("");
  };

  return (
    <div className="relative flex h-full min-h-0 w-full bg-black text-white">
      {/* Sidebar */}
      <div
        className={`${sidebarOpen ? "w-80" : "w-0"} bg-zinc-900 border-r border-zinc-800 flex flex-col transition-all duration-300 overflow-hidden`}
      >
        {/* Sidebar Header */}
        <div className="p-4 border-b border-zinc-800 flex-shrink-0">
          <div className="flex items-center justify-between mb-4">
            <button
              onClick={() => setSidebarOpen(!sidebarOpen)}
              className="p-2 hover:bg-zinc-800 rounded-lg transition"
            >
              <Menu className="w-6 h-6" />
            </button>
            <button className="p-2 hover:bg-zinc-800 rounded-lg transition">
              <Search className="w-6 h-6" />
            </button>
          </div>

          {/* New Chat Button */}
          <button
            onClick={handleNewChat}
            className="w-full px-4 py-3 bg-zinc-800 hover:bg-zinc-700 rounded-lg flex items-center gap-3 transition border border-zinc-700"
          >
            <Plus className="w-5 h-5" />
            <span className="font-medium">New chat</span>
          </button>
        </div>

        {/* Chat History - Scrollable */}
        <div className="flex-1 overflow-y-auto min-h-0">
          {/* Recent Section */}
          <div className="p-4">
            <h3 className="text-sm font-semibold text-zinc-500 mb-3">Recent</h3>
            <div className="space-y-1">
              {chats
                .filter((chat) => chat.recent)
                .map((chat) => (
                  <div key={chat.id} className="flex items-center gap-2">
                    <button
                      onClick={() => setActiveChatId(chat.id)}
                      className={`flex-1 px-4 py-2.5 text-left hover:bg-zinc-800 rounded-lg transition text-sm ${
                        activeChatId === chat.id ? "bg-zinc-800" : ""
                      }`}
                    >
                      {chat.title}
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDeleteChat(chat.id);
                      }}
                      className="p-1 text-[11px] text-zinc-500 hover:text-red-400 hover:bg-zinc-900 rounded-lg transition"
                      aria-label="Delete chat"
                    >
                      ✕
                    </button>
                  </div>
                ))}
            </div>
          </div>

          {/* Other Chats */}
          <div className="p-4 border-t border-zinc-800">
            <div className="space-y-1">
              {chats
                .filter((chat) => !chat.recent)
                .map((chat) => (
                  <div key={chat.id} className="flex items-center gap-2">
                    <button
                      onClick={() => setActiveChatId(chat.id)}
                      className={`flex-1 px-4 py-2.5 text-left hover:bg-zinc-800 rounded-lg transition text-sm ${
                        activeChatId === chat.id ? "bg-zinc-800" : ""
                      }`}
                    >
                      {chat.title}
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDeleteChat(chat.id);
                      }}
                      className="p-1 text-[11px] text-zinc-500 hover:text-red-400 hover:bg-zinc-900 rounded-lg transition"
                      aria-label="Delete chat"
                    >
                      ✕
                    </button>
                  </div>
                ))}
            </div>
          </div>
        </div>

        {/* User Profile */}
        <div className="p-4 border-t border-zinc-800 flex-shrink-0">
          <button className="w-full px-4 py-3 hover:bg-zinc-800 rounded-lg transition flex items-center gap-3">
            <div className="w-8 h-8 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full flex items-center justify-center text-sm font-semibold">
              SK
            </div>
            <span className="font-medium">Sanjay Kumar</span>
          </button>
        </div>
      </div>

      {/* Main Chat Area */}
      <div className="flex-1 flex flex-col relative">
        {/* Top Header */}
        <div className="h-16 border-b border-zinc-800 flex items-center px-6">
          {!sidebarOpen && (
            <button
              onClick={() => setSidebarOpen(true)}
              className="p-2 hover:bg-zinc-800 rounded-lg transition mr-4"
            >
              <Menu className="w-6 h-6" />
            </button>
          )}
          <h1 className="text-2xl font-bold flex-1 text-center">Study guru</h1>
        </div>

        {/* Scrollable Chat Section */}
        <div className="flex-1 overflow-y-auto px-6 pt-8 pb-40">
          <div className="max-w-3xl mx-auto space-y-6">
            {activeChat && activeChat.messages.length === 0 ? (
              <div className="flex items-center justify-center h-full">
                <div className="text-center">
                  <div className="w-16 h-16 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full flex items-center justify-center mx-auto mb-4">
                    <span className="text-2xl">💡</span>
                  </div>
                  <h2 className="text-2xl font-bold text-white mb-2">
                    Start a new conversation
                  </h2>
                  <p className="text-zinc-500">Ask me anything about your studies!</p>
                </div>
              </div>
            ) : (
              activeChat &&
              activeChat.messages.map((msg, index) =>
                msg.role === "user" ? (
                  <div key={index} className="flex justify-end">
                    <div className="bg-zinc-800 rounded-2xl rounded-tr-sm px-6 py-4 max-w-lg">
                      <p className="text-white">{msg.content}</p>
                    </div>
                  </div>
                ) : (
                  <div key={index} className="flex justify-start">
                    <div className="bg-zinc-900 border border-zinc-800 rounded-2xl rounded-tl-sm px-6 py-4 max-w-2xl">
                      <div className="flex items-start gap-3">
                        <div className="w-6 h-6 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full flex-shrink-0 mt-1" />
                        <div>
                          <p className="text-white leading-relaxed">{msg.content}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                )
              )
            )}
          </div>
        </div>

        {/* Input Area fixed at viewport bottom */}
        <div className="fixed bottom-0 left-0 right-0 border-t border-zinc-800 p-4 sm:p-6 bg-black/95">
          <div className="max-w-3xl mx-auto">
            <div className="relative">
              <input
                type="text"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    e.preventDefault();
                    handleSend();
                  }
                }}
                placeholder="Ask study guru"
                className="w-full bg-zinc-900 border border-zinc-800 rounded-full px-6 py-4 pr-14 text-white placeholder-zinc-500 focus:outline-none focus:border-zinc-700 transition"
              />
              <button
                onClick={handleSend}
                className="absolute right-2 top-1/2 -translate-y-1/2 w-10 h-10 bg-white hover:bg-zinc-200 rounded-full flex items-center justify-center transition"
              >
                <Send className="w-5 h-5 text-black" />
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="absolute bottom-1 right-3 text-[10px] text-zinc-500/70 pointer-events-none select-none">
        SG v7
      </div>
    </div>
  );
};
